#!/usr/bin/env python3
"""Generate the website skill index from SKILL.md frontmatter."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from check_skills import ROOT, iter_skill_files, parse_frontmatter


OUTPUT_PATH = ROOT / "website" / "skills-data.js"
CATEGORY_ORDER = {
    "product": 0,
    "codebase": 1,
    "delivery": 2,
    "tech-debt": 3,
    "harness": 4,
}
SKILL_ORDER = [
    "team-concept-whitepaper",
    "team-spec-refine",
    "team-spec-review",
    "team-spec-to-prd",
    "team-spec-archive",
    "team-codebase-onboarding",
    "team-codebase-walk",
    "team-codebase-brief",
    "team-codebase-readme",
    "team-prd-to-alignment",
    "team-prd-to-issues",
    "team-issue-publish-github",
    "team-issue-publish-gitlab",
    "team-issue-batch-implement",
    "team-issue-implement",
    "team-issue-verify",
    "team-issue-create-pr-github",
    "team-issue-create-mr-gitlab",
    "team-tech-debt-analyze",
    "team-tech-debt-refine",
    "team-tech-debt-review",
    "team-tech-debt-to-issues",
    "team-codex-harness",
    "team-skill-evolve",
]
DESCRIPTION_SPLIT = re.compile(r"^(.*?[。！？])\s*([A-Z].*)$", re.DOTALL)


def split_description(description: str, source: Path) -> tuple[str, str]:
    """Split the repository's bilingual description into Chinese and English."""
    match = DESCRIPTION_SPLIT.match(description.strip())
    if not match:
        relative_source = source.relative_to(ROOT)
        raise ValueError(
            f"{relative_source}: description must be Chinese followed by English"
        )
    return match.group(1).strip(), match.group(2).strip()


def build_records() -> list[dict[str, object]]:
    """Read and normalize the public metadata for every team skill."""
    records: list[dict[str, object]] = []
    known_order = {name: index for index, name in enumerate(SKILL_ORDER)}

    for path in iter_skill_files():
        data, errors = parse_frontmatter(path)
        if errors:
            relative_path = path.relative_to(ROOT)
            raise ValueError(f"{relative_path}: {'; '.join(errors)}")

        name = data.get("name")
        description = data.get("description")
        triggers = data.get("triggers")
        metadata = data.get("metadata")
        category = path.parent.parent.name

        if not isinstance(name, str):
            raise ValueError(f"{path.relative_to(ROOT)}: missing skill name")
        if not isinstance(description, str):
            raise ValueError(f"{path.relative_to(ROOT)}: missing description")
        if not isinstance(triggers, list):
            raise ValueError(f"{path.relative_to(ROOT)}: triggers must be a list")
        if not isinstance(metadata, dict):
            raise ValueError(f"{path.relative_to(ROOT)}: metadata must be a mapping")

        description_zh, description_en = split_description(description, path)
        records.append(
            {
                "name": name,
                "category": category,
                "description": {
                    "zh": description_zh,
                    "en": description_en,
                },
                "triggers": [str(trigger) for trigger in triggers],
                "version": str(metadata.get("version", "")),
                "experimental": category == "harness",
            }
        )

    records.sort(
        key=lambda record: (
            CATEGORY_ORDER.get(str(record["category"]), len(CATEGORY_ORDER)),
            known_order.get(str(record["name"]), len(known_order)),
            str(record["name"]),
        )
    )
    return records


def render_output(records: list[dict[str, object]]) -> str:
    """Render a browser-ready, deterministic JavaScript data file."""
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/build_website_data.py. Do not edit by hand.\n"
        f"window.SRT_SKILLS = Object.freeze({payload});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate website/skills-data.js from SKILL.md frontmatter."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed website data does not match the skill sources.",
    )
    args = parser.parse_args()

    try:
        records = build_records()
        expected = render_output(records)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1

    if args.check:
        if not OUTPUT_PATH.exists():
            print(
                f"{OUTPUT_PATH.relative_to(ROOT)} is missing; run this script to generate it",
                file=sys.stderr,
            )
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print(
                f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run this script to regenerate it",
                file=sys.stderr,
            )
            return 1
        print(f"Website skill data is current ({len(records)} skills).")
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)} ({len(records)} skills).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
