// Generated by scripts/build_website_data.py. Do not edit by hand.
window.SRT_SKILLS = Object.freeze([
  {
    "name": "team-concept-whitepaper",
    "category": "product",
    "description": {
      "zh": "在产品规划阶段澄清产品定位、价值与能力边界，并编写可评审的产品概念白皮书。",
      "en": "Create a reviewable product concept white paper by clarifying its positioning, value, and capability boundaries."
    },
    "triggers": [
      "编写产品概念白皮书",
      "写产品白皮书",
      "梳理产品概念",
      "定义产品定位和边界",
      "产品规划阶段需要白皮书",
      "write a product concept white paper",
      "create a product white paper",
      "clarify a product concept",
      "define product positioning and boundaries",
      "document a product vision"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-refine",
    "category": "product",
    "description": {
      "zh": "通过用户确认细化需求规格，澄清术语、边界、业务规则和验收口径。",
      "en": "Refine product specs through user confirmation of terminology, scope, business rules, and acceptance criteria."
    },
    "triggers": [
      "细化需求",
      "需求不清楚",
      "打磨规格",
      "帮我想清楚这个需求",
      "需求还没想好",
      "refine spec",
      "clarify requirements",
      "spec is unclear",
      "help me think through this requirement"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-review",
    "category": "product",
    "description": {
      "zh": "评审已细化的需求规格，输出风险、阻塞项、补救动作和 ready 结论。",
      "en": "Review refined product specs and produce risks, blockers, mitigations, and readiness findings."
    },
    "triggers": [
      "评审规格",
      "规格准备好了吗",
      "检查需求风险",
      "这个需求有没有风险",
      "规格 ready 了吗",
      "review spec",
      "spec ready check",
      "check requirement risks",
      "is the spec ready"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-to-prd",
    "category": "product",
    "description": {
      "zh": "将已细化并通过评审的规格固化为结构化 PRD，形成需求到工程的交接边界。",
      "en": "Turn refined and reviewed specs into a structured PRD as the product-to-engineering handoff boundary."
    },
    "triggers": [
      "写 PRD",
      "生成 PRD",
      "规格转 PRD",
      "固化 PRD",
      "规格已经 ready 了",
      "需求 ready 写 PRD",
      "write PRD",
      "generate PRD",
      "turn spec into PRD",
      "spec is ready produce PRD",
      "produce PRD from reviewed spec"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-archive",
    "category": "product",
    "description": {
      "zh": "将已完成、废弃或暂停的单个需求工作区从 active 归档到 archive。",
      "en": "Archive one completed, abandoned, or paused requirement workspace from active to archive."
    },
    "triggers": [
      "归档需求",
      "归档 active 需求",
      "结束这个需求",
      "暂停这个需求",
      "归档这个 slug",
      "archive spec",
      "archive requirement",
      "archive active spec",
      "close this requirement",
      "archive this slug"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codebase-onboarding",
    "category": "codebase",
    "description": {
      "zh": "从已有代码仓库提取可追溯的功能清单、架构说明和 AI 接手上下文。",
      "en": "Extract traceable feature inventory, architecture notes, and AI onboarding context from an existing codebase."
    },
    "triggers": [
      "熟悉代码库",
      "生成项目功能清单",
      "从源码生成设计文档",
      "生成代码库文档",
      "梳理开源项目",
      "大型代码库接手",
      "通信系统代码分析",
      "codebase onboarding",
      "generate feature inventory",
      "reverse engineer design docs",
      "generate codebase documentation",
      "understand an unfamiliar repository",
      "large C++ codebase onboarding",
      "telecom codebase analysis"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codebase-walk",
    "category": "codebase",
    "description": {
      "zh": "基于 onboarding 产物和源码，围绕功能清单做代码库走读、问答和证据追踪。",
      "en": "Guide developers through codebase features with walkthroughs, Q&A, and source-backed explanations."
    },
    "triggers": [
      "代码走读",
      "带我理解代码",
      "深入分析某个模块",
      "解释这个功能怎么实现",
      "根据文档继续问代码",
      "选择功能走读",
      "按功能理解代码",
      "引导我看 feature",
      "梳理修改路径",
      "codebase walkthrough",
      "guided code reading",
      "feature walkthrough",
      "walk through features",
      "explain this module",
      "deep dive into code",
      "codebase Q&A",
      "trace implementation path"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codebase-brief",
    "category": "codebase",
    "description": {
      "zh": "将代码库事实转化为面向业务、产品和管理者的能力说明、场景材料和影响分析。",
      "en": "Turn codebase evidence into business-facing capability briefs, scenario narratives, and impact analysis."
    },
    "triggers": [
      "生成业务分享材料",
      "给产品讲代码能力",
      "代码库业务解读",
      "系统能力说明",
      "产品影响分析",
      "面向业务汇报",
      "codebase brief",
      "business-facing codebase summary",
      "product-facing technical brief",
      "explain codebase to product",
      "capability brief",
      "stakeholder alignment"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codebase-readme",
    "category": "codebase",
    "description": {
      "zh": "创建、审阅和优化团队自有项目 README.md，以准确事实和自上而下的信息层级呈现定位、快速开始、使用与维护入口。",
      "en": "Create, review, and improve README.md for team-owned projects using verified facts and a progressive top-to-bottom reading flow."
    },
    "triggers": [
      "编写项目 README",
      "创建 README.md",
      "优化项目 README",
      "重写项目介绍",
      "create a project README",
      "review this README",
      "improve repository documentation",
      "rewrite the project README"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-prd-to-alignment",
    "category": "delivery",
    "description": {
      "zh": "将结构化 PRD 转换为适合需求、研发和项目管理评审的对齐材料。",
      "en": "Turn structured PRDs into alignment materials for product, engineering, and project management review."
    },
    "triggers": [
      "PRD 对齐材料",
      "PRD 转评审材料",
      "生成需求研发对齐文档",
      "PRD 给人看",
      "需求研发对齐",
      "生成评审会材料",
      "PRD alignment material",
      "turn PRD into review material",
      "create PRD alignment deck",
      "make PRD human readable",
      "product engineering alignment",
      "create review meeting material"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-prd-to-issues",
    "category": "delivery",
    "description": {
      "zh": "将 PRD 拆解为可独立领取、可验证、按依赖排序的端到端工程 issue。",
      "en": "Break PRDs into independently grabbable, verifiable, dependency-ordered engineering issues."
    },
    "triggers": [
      "拆 issue",
      "把 PRD 拆成任务",
      "工程 issue 拆解",
      "PRD 已经确认了开始拆工程任务",
      "生成工程任务",
      "break PRD into issues",
      "create issues from PRD",
      "PRD is approved start issue breakdown",
      "write engineering issues"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-issue-publish-github",
    "category": "delivery",
    "description": {
      "zh": "将本地工程 issue 草稿发布到 GitHub Issues，并回写发布结果。",
      "en": "Publish local engineering issue drafts to GitHub Issues and write back publication status."
    },
    "triggers": [
      "发布到 GitHub",
      "发布 issue 到 GitHub",
      "批量创建 GitHub Issues",
      "把 issue 草稿发布到 GitHub",
      "发布单个 issue 到 GitHub",
      "帮我发 GitHub issue",
      "publish to GitHub",
      "publish issue to GitHub",
      "create GitHub issues from drafts",
      "create GitHub issue from draft",
      "batch publish issues to GitHub",
      "publish issue drafts to GitHub"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-issue-publish-gitlab",
    "category": "delivery",
    "description": {
      "zh": "将本地工程 issue 草稿发布到 GitLab Issues，并回写发布结果。",
      "en": "Publish local engineering issue drafts to GitLab Issues and write back publication status."
    },
    "triggers": [
      "发布到 GitLab",
      "发布 issue 到 GitLab",
      "批量创建 GitLab Issues",
      "把 issue 草稿发布到 GitLab",
      "发布单个 issue 到 GitLab",
      "帮我发 GitLab issue",
      "publish to GitLab",
      "publish issue to GitLab",
      "create GitLab issues from drafts",
      "create GitLab issue from draft",
      "batch publish issues to GitLab",
      "publish issue drafts to GitLab"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-issue-batch-implement",
    "category": "delivery",
    "description": {
      "zh": "按依赖顺序批量编排多个工程 issue 的实现与验证，并保留失败即停和可恢复续跑边界。",
      "en": "Batch orchestrate multiple engineering issues in dependency order with verification, fail-fast behavior, and resumable boundaries."
    },
    "triggers": [
      "批量实现 issue",
      "连续处理多个 issue",
      "批量跑工程任务",
      "一次实现多个 AFK issue",
      "批量最小改动实现",
      "批量不要过度设计",
      "不要扩大 issue 范围",
      "batch implement issues",
      "implement multiple issues",
      "run issue queue",
      "process AFK issues in bulk",
      "lean batch implementation",
      "avoid batch over-engineering",
      "keep issue scope minimal"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-issue-implement",
    "category": "delivery",
    "description": {
      "zh": "实现单个工程 issue，优先使用行为测试、TDD、现有代码复用和最小实现模式。",
      "en": "Implement one engineering issue with behavior-focused tests, TDD, existing-code reuse, and lean implementation."
    },
    "triggers": [
      "实现 issue",
      "开始写代码",
      "按 issue 编码",
      "实现这个功能",
      "最小改动实现",
      "不要过度设计",
      "简单实现",
      "优先复用现有代码",
      "少写代码",
      "implement issue",
      "start coding",
      "implement this feature",
      "code this issue",
      "minimal implementation",
      "avoid over-engineering",
      "reuse existing code first",
      "simplest correct change"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-issue-verify",
    "category": "delivery",
    "description": {
      "zh": "独立验证单个 issue 实现是否满足验收、PRD、风险和最小实现要求。",
      "en": "Verify a single issue implementation against acceptance criteria, PRD, risks, and lean implementation expectations."
    },
    "triggers": [
      "验证实现",
      "检查 issue 是否完成",
      "能提 PR 了吗",
      "实现完了帮我验一下",
      "检查是否过度设计",
      "看看有没有写复杂",
      "最小实现验收",
      "简化审查",
      "审查 diff 有没有过度设计",
      "看看能删掉什么",
      "verify issue",
      "check implementation",
      "ready for PR",
      "is this implementation complete",
      "over-engineering review",
      "check lean implementation",
      "review unnecessary complexity",
      "simplify review",
      "review diff complexity",
      "what can be deleted"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-issue-create-pr-github",
    "category": "delivery",
    "description": {
      "zh": "为已完成的单个 issue 分支推送代码并创建关联 issue 的 GitHub Pull Request。",
      "en": "Push a completed issue branch and create an issue-linked GitHub Pull Request."
    },
    "triggers": [
      "创建 GitHub PR",
      "创建 Pull Request",
      "给这个 issue 建 PR",
      "推送分支并创建 PR",
      "准备提 PR",
      "create GitHub PR",
      "open pull request",
      "create pull request for issue",
      "push branch and open PR",
      "open PR for this issue"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-issue-create-mr-gitlab",
    "category": "delivery",
    "description": {
      "zh": "为已完成的单个 issue 分支推送代码并创建关联 issue 的 GitLab Merge Request。",
      "en": "Push a completed issue branch and create an issue-linked GitLab Merge Request."
    },
    "triggers": [
      "创建 GitLab MR",
      "创建合并请求",
      "给这个 issue 建 MR",
      "推送分支并创建 MR",
      "准备提 MR",
      "create GitLab MR",
      "open merge request",
      "create merge request for issue",
      "push branch and open MR",
      "open MR for this issue"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-tech-debt-analyze",
    "category": "tech-debt",
    "description": {
      "zh": "对项目或模块进行只读技术债分析，输出有证据的维护性、稳定性、测试、架构和交付风险报告。",
      "en": "Analyze technical debt through read-only inspection and produce evidence-backed maintainability, stability, testing, architecture, and delivery risk findings."
    },
    "triggers": [
      "分析技术债",
      "代码健康检查",
      "找维护风险",
      "看看项目有哪些技术债",
      "分析过度设计",
      "查无用抽象",
      "找不必要依赖",
      "复杂度审计",
      "收集延迟债务",
      "收集 team-minimal 注释",
      "technical debt analysis",
      "code health review",
      "maintainability audit",
      "find technical debt",
      "find over-engineering",
      "unnecessary abstraction audit",
      "dependency simplification review",
      "complexity audit",
      "collect deferred debt",
      "collect team-minimal comments"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-tech-debt-refine",
    "category": "tech-debt",
    "description": {
      "zh": "通过用户确认细化技术债需求，明确证据、影响范围、风险等级和验收口径。",
      "en": "Refine technical debt requests through user confirmation of evidence, scope, risk, and acceptance criteria."
    },
    "triggers": [
      "技术债细化",
      "梳理技术债",
      "技术债需求说不清楚",
      "帮我想清楚这个技术债",
      "技术债验收怎么定",
      "refine tech debt",
      "clarify tech debt",
      "tech debt is unclear",
      "define tech debt acceptance"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-tech-debt-review",
    "category": "tech-debt",
    "description": {
      "zh": "评审技术债规格的风险、优先级、阻塞项和工程拆解 ready 状态。",
      "en": "Review technical debt specs for risk, priority, blockers, and readiness for issue breakdown."
    },
    "triggers": [
      "评审技术债",
      "技术债有没有风险",
      "技术债准备好了吗",
      "技术债 ready 了吗",
      "技术债能拆了吗",
      "review tech debt",
      "tech debt risk review",
      "is tech debt ready for breakdown",
      "ready to create tech debt issues"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-tech-debt-to-issues",
    "category": "tech-debt",
    "description": {
      "zh": "将已评审的技术债规格拆解为可独立领取、可验证、按依赖排序的工程 issue。",
      "en": "Break reviewed technical debt specs into independently grabbable, verifiable, dependency-ordered engineering issues."
    },
    "triggers": [
      "技术债拆 issue",
      "把技术债拆成任务",
      "技术债转工程任务",
      "技术债已经 ready 开始拆任务",
      "break tech debt into issues",
      "create issues from tech debt",
      "split technical debt work",
      "tech debt is ready create issues"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codex-harness",
    "category": "harness",
    "description": {
      "zh": "为具体代码项目维护 Codex 运行时检索层、入口约束、失败记忆和验证 harness。",
      "en": "Maintain a Codex runtime retrieval layer, entry constraints, failure memory, and verification harness for a concrete code project."
    },
    "triggers": [
      "维护 Codex harness",
      "改进 AGENTS.md",
      "Codex 不知道怎么验证",
      "沉淀 Codex 失败记忆",
      "Codex 找不到任务入口",
      "Codex 需要入口约束",
      "Codex 需要配置引导",
      "maintain Codex harness",
      "improve AGENTS.md",
      "Codex failure memory",
      "Codex verification harness",
      "Codex task entry points",
      "Codex entry constraints",
      "Codex runtime config"
    ],
    "version": "1.0",
    "experimental": true
  },
  {
    "name": "team-skill-evolve",
    "category": "harness",
    "description": {
      "zh": "根据真实反馈、失败案例和执行日志复盘团队技能库，并提出可审核的技能进化建议。",
      "en": "Review real feedback, failures, and execution logs to propose auditable improvements to the team skill library."
    },
    "triggers": [
      "技能复盘",
      "改进技能",
      "技能自进化",
      "根据反馈优化 skill",
      "复盘 agent 失败",
      "优化触发词",
      "技能过度设计",
      "技能写太多代码",
      "没有复用现有代码",
      "skill evolution",
      "improve this skill",
      "review skill feedback",
      "refine agent workflow",
      "analyze agent failure",
      "update skill triggers",
      "skill over-engineered",
      "agent wrote too much code",
      "missed existing reuse"
    ],
    "version": "1.0",
    "experimental": true
  }
]);
