// Generated by scripts/build_website_data.py. Do not edit by hand.
window.SRT_SKILLS = Object.freeze([
  {
    "name": "team-config-init",
    "category": "config",
    "description": {
      "zh": "初始化、校验并增量补全 team-spec/config.yml，集中管理语言、版本控制、访问策略和写作风格入口。",
      "en": "Initialize, validate, and safely complete shared team-spec project configuration."
    },
    "triggers": [
      "初始化团队配置",
      "创建 team-spec 配置",
      "补全项目运行时配置",
      "initialize team config",
      "create team-spec config",
      "complete project configuration"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-concept-whitepaper",
    "category": "product",
    "description": {
      "zh": "在产品规划阶段澄清产品定位、价值与能力边界，并编写可评审的产品概念白皮书。",
      "en": "Create a reviewable product concept white paper by clarifying its positioning, value, and capability boundaries."
    },
    "triggers": [
      "编写产品概念白皮书",
      "写产品白皮书",
      "梳理产品概念",
      "定义产品定位和边界",
      "产品规划阶段需要白皮书",
      "write a product concept white paper",
      "create a product white paper",
      "clarify a product concept",
      "define product positioning and boundaries",
      "document a product vision"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-discovery-robotics",
    "category": "product",
    "description": {
      "zh": "将机器人场景或既有本体适配需求转化为有证据的软硬件、算法与实施方案。",
      "en": "Turn robotics scenarios or fixed-platform constraints into evidence-backed solution and software specifications."
    },
    "triggers": [
      "梳理机器人场景需求",
      "访谈机器人客户需求",
      "具身智能需求不清楚",
      "规划机器人场景 MVP",
      "和客户现场逐问需求",
      "生成异步机器人访谈问题",
      "设计机器人软硬件方案",
      "编写机器人软件算法规格",
      "推荐机器人和传感器型号",
      "评估场景是否适配现有机器人",
      "基于指定机器人本体设计方案",
      "比较 VLA 技术方案",
      "检索最新机器人技术选型",
      "discover robotics requirements",
      "scope a robotics scenario",
      "interview for embodied AI needs",
      "define a robotics MVP",
      "run a live robotics discovery interview",
      "prepare asynchronous robotics discovery questions",
      "design a robotics solution",
      "specify robotics software and algorithms",
      "recommend robot and sensor models",
      "assess scenario fit for an existing robot",
      "design around a fixed robot platform",
      "compare VLA technology options",
      "research current robotics technology choices"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-refine",
    "category": "product",
    "description": {
      "zh": "通过用户确认细化需求规格，澄清术语、边界、业务规则和验收口径。",
      "en": "Refine product specs through user confirmation of terminology, scope, business rules, and acceptance criteria."
    },
    "triggers": [
      "细化需求",
      "需求不清楚",
      "打磨规格",
      "帮我想清楚这个需求",
      "需求还没想好",
      "refine spec",
      "clarify requirements",
      "spec is unclear",
      "help me think through this requirement"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-review",
    "category": "product",
    "description": {
      "zh": "评审已细化的需求规格，输出风险、阻塞项、补救动作和 ready 结论。",
      "en": "Review refined product specs and produce risks, blockers, mitigations, and readiness findings."
    },
    "triggers": [
      "评审规格",
      "规格准备好了吗",
      "检查需求风险",
      "这个需求有没有风险",
      "规格 ready 了吗",
      "review spec",
      "spec ready check",
      "check requirement risks",
      "is the spec ready"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-to-prd",
    "category": "product",
    "description": {
      "zh": "将已细化并通过评审的规格固化为结构化 PRD，形成需求到工程的交接边界。",
      "en": "Turn refined and reviewed specs into a structured PRD as the product-to-engineering handoff boundary."
    },
    "triggers": [
      "写 PRD",
      "生成 PRD",
      "规格转 PRD",
      "固化 PRD",
      "规格已经 ready 了",
      "需求 ready 写 PRD",
      "write PRD",
      "generate PRD",
      "turn spec into PRD",
      "spec is ready produce PRD",
      "produce PRD from reviewed spec"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-archive",
    "category": "product",
    "description": {
      "zh": "将已完成、废弃或暂停的单个需求工作区从 active 归档到 archive。",
      "en": "Archive one completed, abandoned, or paused requirement workspace from active to archive."
    },
    "triggers": [
      "归档需求",
      "归档 active 需求",
      "结束这个需求",
      "暂停这个需求",
      "归档这个 slug",
      "archive spec",
      "archive requirement",
      "archive active spec",
      "close this requirement",
      "archive this slug"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codebase-onboarding",
    "category": "codebase",
    "description": {
      "zh": "从已有代码仓库提取可追溯的功能清单、架构说明和 AI 接手上下文。",
      "en": "Extract traceable feature inventory, architecture notes, and AI onboarding context from an existing codebase."
    },
    "triggers": [
      "熟悉代码库",
      "生成项目功能清单",
      "从源码生成设计文档",
      "生成代码库文档",
      "梳理开源项目",
      "大型代码库接手",
      "通信系统代码分析",
      "codebase onboarding",
      "generate feature inventory",
      "reverse engineer design docs",
      "generate codebase documentation",
      "understand an unfamiliar repository",
      "large C++ codebase onboarding",
      "telecom codebase analysis"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codebase-walk",
    "category": "codebase",
    "description": {
      "zh": "基于 onboarding 产物和源码，围绕功能清单做代码库走读、问答和证据追踪。",
      "en": "Guide developers through codebase features with walkthroughs, Q&A, and source-backed explanations."
    },
    "triggers": [
      "代码走读",
      "带我理解代码",
      "深入分析某个模块",
      "解释这个功能怎么实现",
      "根据文档继续问代码",
      "选择功能走读",
      "按功能理解代码",
      "引导我看 feature",
      "梳理修改路径",
      "codebase walkthrough",
      "guided code reading",
      "feature walkthrough",
      "walk through features",
      "explain this module",
      "deep dive into code",
      "codebase Q&A",
      "trace implementation path"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codebase-brief",
    "category": "codebase",
    "description": {
      "zh": "将代码库事实转化为面向业务、产品和管理者的能力说明、场景材料和影响分析。",
      "en": "Turn codebase evidence into business-facing capability briefs, scenario narratives, and impact analysis."
    },
    "triggers": [
      "生成业务分享材料",
      "给产品讲代码能力",
      "代码库业务解读",
      "系统能力说明",
      "产品影响分析",
      "面向业务汇报",
      "codebase brief",
      "business-facing codebase summary",
      "product-facing technical brief",
      "explain codebase to product",
      "capability brief",
      "stakeholder alignment"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-codebase-readme",
    "category": "codebase",
    "description": {
      "zh": "创建、审阅和优化团队自有项目 README.md，以准确事实和自上而下的信息层级呈现定位、快速开始、使用与维护入口。",
      "en": "Create, review, and improve README.md for team-owned projects using verified facts and a progressive top-to-bottom reading flow."
    },
    "triggers": [
      "编写项目 README",
      "创建 README.md",
      "优化项目 README",
      "重写项目介绍",
      "create a project README",
      "review this README",
      "improve repository documentation",
      "rewrite the project README"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-prd-to-brief",
    "category": "delivery",
    "description": {
      "zh": "将结构化 PRD 转换为适合需求、研发和项目管理评审的简报。",
      "en": "Turn structured PRDs into review briefs for product, engineering, and project management."
    },
    "triggers": [
      "PRD 简报",
      "PRD 转评审简报",
      "生成需求研发对齐文档",
      "PRD 给人看",
      "需求研发对齐",
      "生成评审会材料",
      "PRD review brief",
      "turn PRD into review brief",
      "create PRD brief",
      "make PRD human readable",
      "product engineering alignment",
      "create review meeting material"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-prd-to-tasks",
    "category": "delivery",
    "description": {
      "zh": "将 PRD 拆解为可独立实现、验证并在用户确认差异后提交的工程 Task。",
      "en": "Break a PRD into dependency-ordered tasks that each produce one user-confirmed local commit after verification."
    },
    "triggers": [
      "拆 Task",
      "把 PRD 拆成工程任务",
      "生成可提交的开发任务",
      "break PRD into tasks",
      "create engineering tasks",
      "plan commit-sized tasks"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-create-issue-github",
    "category": "delivery",
    "description": {
      "zh": "将完整 Spec 创建或同步为一个 GitHub Issue，并用 checklist 汇总其所有 Tasks。",
      "en": "Create or sync one GitHub Issue for a complete spec, with all local tasks represented as a checklist."
    },
    "triggers": [
      "为 Spec 创建 GitHub Issue",
      "发布完整需求到 GitHub",
      "同步需求跟踪 Issue",
      "create GitHub issue for spec",
      "publish spec to GitHub",
      "sync spec tracking issue"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-create-issue-gitlab",
    "category": "delivery",
    "description": {
      "zh": "将完整 Spec 创建或同步为一个 GitLab Issue，并用 checklist 汇总其所有 Tasks。",
      "en": "Create or sync one GitLab Issue for a complete spec, with all local tasks represented as a checklist."
    },
    "triggers": [
      "为 Spec 创建 GitLab Issue",
      "发布完整需求到 GitLab",
      "同步需求跟踪 Issue",
      "create GitLab issue for spec",
      "publish spec to GitLab",
      "sync spec tracking issue"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-task-batch-implement",
    "category": "delivery",
    "description": {
      "zh": "在同一 Spec 分支按依赖顺序批量实现多个 Task，每个 Task 验证后等待用户检查差异并确认提交。",
      "en": "Batch implement tasks on one shared spec branch with per-task diff review and commit confirmation."
    },
    "triggers": [
      "批量实现 Task",
      "连续处理多个工程任务",
      "在同一分支完成所有任务",
      "batch implement tasks",
      "implement multiple tasks",
      "complete tasks on one branch"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-task-implement",
    "category": "delivery",
    "description": {
      "zh": "在 Spec 共享分支实现单个工程 Task，验证通过并经用户检查差异、明确确认后创建本地逻辑 commit。",
      "en": "Implement one task on its shared spec branch, pausing for user diff review and confirmation before the local commit."
    },
    "triggers": [
      "实现 Task",
      "开始工程任务",
      "实现并提交这个任务",
      "implement task",
      "start task coding",
      "implement and commit task"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-task-verify",
    "category": "delivery",
    "description": {
      "zh": "独立验证单个 Task 实现是否满足验收、PRD、风险和最小实现要求。",
      "en": "Independently verify one task implementation against its acceptance criteria, parent spec, risks, and commit boundary."
    },
    "triggers": [
      "验证 Task",
      "检查工程任务是否完成",
      "这个任务可以提交了吗",
      "verify task",
      "review task implementation",
      "is this task ready to commit"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-create-pr-github",
    "category": "delivery",
    "description": {
      "zh": "推送一个 Spec 的共享分支，并为其全部已提交 Tasks 创建一个 GitHub Pull Request。",
      "en": "Push one spec branch and create a single GitHub Pull Request covering all committed tasks in that spec."
    },
    "triggers": [
      "为 Spec 创建 GitHub PR",
      "所有 Task 完成后提 PR",
      "推送需求分支并创建 PR",
      "create GitHub PR for spec",
      "open PR after all tasks",
      "push spec branch and create PR"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-spec-create-mr-gitlab",
    "category": "delivery",
    "description": {
      "zh": "推送一个 Spec 的共享分支，并为其全部已提交 Tasks 创建一个 GitLab Merge Request。",
      "en": "Push one spec branch and create a single GitLab Merge Request covering all committed tasks in that spec."
    },
    "triggers": [
      "为 Spec 创建 GitLab MR",
      "所有 Task 完成后提 MR",
      "推送需求分支并创建 MR",
      "create GitLab MR for spec",
      "open MR after all tasks",
      "push spec branch and create MR"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-tech-debt-analyze",
    "category": "tech-debt",
    "description": {
      "zh": "对项目或模块进行只读技术债分析，输出有证据的维护性、稳定性、测试、架构和交付风险报告。",
      "en": "Analyze technical debt through read-only inspection and produce evidence-backed maintainability, stability, testing, architecture, and delivery risk findings."
    },
    "triggers": [
      "分析技术债",
      "代码健康检查",
      "找维护风险",
      "看看项目有哪些技术债",
      "分析过度设计",
      "查无用抽象",
      "找不必要依赖",
      "复杂度审计",
      "收集延迟债务",
      "收集 team-minimal 注释",
      "technical debt analysis",
      "code health review",
      "maintainability audit",
      "find technical debt",
      "find over-engineering",
      "unnecessary abstraction audit",
      "dependency simplification review",
      "complexity audit",
      "collect deferred debt",
      "collect team-minimal comments"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-tech-debt-refine",
    "category": "tech-debt",
    "description": {
      "zh": "通过用户确认细化技术债需求，明确证据、影响范围、风险等级和验收口径。",
      "en": "Refine technical debt requests through user confirmation of evidence, scope, risk, and acceptance criteria."
    },
    "triggers": [
      "技术债细化",
      "梳理技术债",
      "技术债需求说不清楚",
      "帮我想清楚这个技术债",
      "技术债验收怎么定",
      "refine tech debt",
      "clarify tech debt",
      "tech debt is unclear",
      "define tech debt acceptance"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-tech-debt-review",
    "category": "tech-debt",
    "description": {
      "zh": "评审技术债规格的风险、优先级、阻塞项和工程 Task 拆解 ready 状态。",
      "en": "Review technical debt specs for risk, priority, blockers, and readiness for Task breakdown."
    },
    "triggers": [
      "评审技术债",
      "技术债有没有风险",
      "技术债准备好了吗",
      "技术债 ready 了吗",
      "技术债能拆了吗",
      "review tech debt",
      "tech debt risk review",
      "is tech debt ready for breakdown",
      "ready to create tech debt tasks"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-tech-debt-to-tasks",
    "category": "tech-debt",
    "description": {
      "zh": "将已评审技术债拆为可独立实现、验证并在用户确认差异后提交的 Task。",
      "en": "Break a reviewed technical-debt spec into tasks that each produce one user-confirmed local commit after verification."
    },
    "triggers": [
      "技术债拆 Task",
      "把技术债拆成工程任务",
      "生成技术债开发计划",
      "break technical debt into tasks",
      "create technical debt tasks",
      "plan technical debt commits"
    ],
    "version": "1.0",
    "experimental": false
  },
  {
    "name": "team-archive-distill",
    "category": "harness",
    "description": {
      "zh": "从已归档的 team-spec 中提取决策模式和工程惯例，高度抽象为规则后写入 AGENTS.md。",
      "en": "Extract decision patterns and engineering conventions from archived team-specs, abstract them into high-level rules, and write them into AGENTS.md."
    },
    "triggers": [
      "从归档提取规则",
      "归档决策抽象",
      "更新 AGENTS.md 规则",
      "从历史需求提炼规则",
      "过去决策总结",
      "复盘历史 spec",
      "extract rules from archive",
      "abstract archived decisions",
      "distill rules from past specs",
      "update AGENTS.md from history",
      "summarize past decisions",
      "review archived specs"
    ],
    "version": "1.0",
    "experimental": true
  },
  {
    "name": "team-skill-evolve",
    "category": "harness",
    "description": {
      "zh": "根据真实反馈、失败案例和执行日志复盘团队技能库，并提出可审核的技能进化建议。",
      "en": "Review real feedback, failures, and execution logs to propose auditable improvements to the team skill library."
    },
    "triggers": [
      "技能复盘",
      "改进技能",
      "技能自进化",
      "根据反馈优化 skill",
      "复盘 agent 失败",
      "优化触发词",
      "技能过度设计",
      "技能写太多代码",
      "没有复用现有代码",
      "skill evolution",
      "improve this skill",
      "review skill feedback",
      "refine agent workflow",
      "analyze agent failure",
      "update skill triggers",
      "skill over-engineered",
      "agent wrote too much code",
      "missed existing reuse"
    ],
    "version": "1.0",
    "experimental": true
  },
  {
    "name": "team-writing-style",
    "category": "writing",
    "description": {
      "zh": "为团队项目建立、维护和应用统一的自然语言、代码注释与交互标记风格。",
      "en": "Define and apply a shared writing, code-comment, and interaction-marker style for team projects."
    },
    "triggers": [
      "定义写作风格",
      "去掉 AI 味",
      "统一文档语气",
      "规范代码注释",
      "规范 Emoji 使用",
      "优化机器化表达",
      "define writing style",
      "reduce AI-sounding prose",
      "standardize documentation tone",
      "improve code comment style",
      "standardize emoji usage",
      "humanize team documents"
    ],
    "version": "1.0",
    "experimental": false
  }
]);
